#
# Assignment 9:
#
# Solve this problem from https://projecteuler.net/problem=2:
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.
#





total = 0
numbers = [1, 2]
# Solve the problem here.
while numbers[-1] in range(0, 4000000):
    total = numbers[-1] + numbers[-2]
    numbers.append(total)
total = 0
even_numbers = []
while total < len(numbers):
    if numbers[total] % 2 == 0:
        even_numbers.append(numbers[total])
    total += 1
total = sum(even_numbers)
print("Total is " + str(total))